---
- file:
    path: /opt/pinbot/config
    state: directory
- template:
    src: hosts.j2
    dest: /opt/pinbot/config/hosts
    mode: 0644
  register: pinbot_config

- shell: "cat /opt/pinbot-camp.ref | grep {{ pinbot_camp_ref }}"
  ignore_errors: true
  register: pinbot_camp_ref_present
- git:
    repo: https://github.com/whyrusleeping/pinbot.git
    dest: /opt/pinbot/src-camp
    version: "{{ pinbot_camp_ref }}"
    force: yes
  when: "pinbot_camp_ref_present.rc != 0"
- copy:
    src: Dockerfile
    dest: /opt/pinbot/src-camp/Dockerfile
  when: "pinbot_camp_ref_present.rc != 0"
- shell: "docker build -t pinbot:{{ pinbot_camp_ref }} /opt/pinbot/src-camp"
  when: "pinbot_camp_ref_present.rc != 0"
- name: record new pinbot ref
  shell: "echo {{ pinbot_camp_ref }} > /opt/pinbot-camp.ref"
  when: "pinbot_camp_ref_present.rc != 0"

- command: cp /opt/pinbot/src-camp/friends /opt/pinbot/config
- docker:
    name: pinbot-camp
    image: "pinbot:{{ pinbot_camp_ref }}"
    command: --name=pinbot --server=irc.hackint.org:9999
    state: reloaded
    restart_policy: always
    net: host
    volumes:
      - /opt/pinbot/config:/pinbot

- docker:
    name: pinbot-camp
    image: "pinbot:{{ pinbot_camp_ref }}"
    state: restarted
  when: pinbot_config.changed
