---
- hosts: all
  pre_tasks:
    - include_vars: secrets_plaintext/secrets.yml
  roles:
    - common
    - docker
    - cjdns
    - nginx
    - node_exporter

- hosts: gateway
  vars:
    gateway_group: gateway
  pre_tasks:
    - include_vars: secrets_plaintext/secrets.yml
  handlers:
    - include: roles/nginx/handlers/main.yml
  roles:
    - ipfs
    - ipfs_gateway

- hosts: metrics
  vars:
    gateway_group: gateway
  pre_tasks:
    - include_vars: secrets_plaintext/secrets.yml
  handlers:
    - include: roles/nginx/handlers/main.yml
  roles:
    - metrics

- hosts: util
  vars:
    gateway_group: gateway
  pre_tasks:
    - include_vars: secrets_plaintext/secrets.yml
  handlers:
    - include: roles/nginx/handlers/main.yml
  roles:
    - pinbot
    - pinbot-camp
